import { PublicShell } from "@/components/PublicShell";
import { Button } from "@/components/ui/button";
import { HAS_PLATFORM_API } from "@/lib/runtime";
import { ArrowRight, CheckCircle2, Database, Github, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function LaunchStatus() {
  return <PublicShell><section className="page-hero"><div className="container py-20 sm:py-28"><p className="eyebrow">GitHub launch</p><h1 className="display mt-5 max-w-5xl text-7xl leading-[.88] sm:text-8xl">AiR is live.<br /><em>Keep building.</em></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-mist">The public learning site is hosted on GitHub. Member accounts, saved progress, community posts, uploads, and administrator tools connect through AiR’s secure server.</p></div></section><section className="paths-section py-16"><div className="container grid gap-5 lg:grid-cols-2"><article className="rounded-[2rem] border border-[var(--hairline)] bg-[var(--surface-raised)] p-7 sm:p-10"><Github className="size-7 text-[var(--go)]" /><h2 className="display mt-6 text-5xl">Public site</h2><p className="mt-4 leading-8 text-mist">Brand story, learning paths, lesson summaries, campaign work, themes, and the age-eight-friendly AiR method are available now.</p><Link href="/curriculum"><Button className="air-button mt-7">Explore lessons <ArrowRight /></Button></Link></article><article className="rounded-[2rem] border border-[var(--hairline)] bg-[var(--surface-raised)] p-7 sm:p-10">{HAS_PLATFORM_API ? <CheckCircle2 className="size-7 text-[var(--go)]" /> : <Database className="size-7 text-[var(--spark)]" />}<h2 className="display mt-6 text-5xl">Member tools</h2><p className="mt-4 leading-8 text-mist">{HAS_PLATFORM_API ? "The secure AiR server is connected. You can sign in and continue your learning journey." : "The GitHub site is ready. Connect the published AiR server to turn on sign-in, saved progress, community rooms, course uploads, and admin tools."}</p><div className="mt-7 flex items-center gap-3 text-sm font-bold"><ShieldCheck className="size-5" /> Your learning data belongs on the secure server—not in a public repository.</div></article></div></section></PublicShell>;
}
